# Generated by Django 6.0.4 on 2026-05-02 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dbuser_remove_expense_user_remove_savingsgoal_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbexpense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dbexpense',
            name='date',
        ),
        migrations.AddField(
            model_name='dbexpense',
            name='user_id',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dbexpense',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='DBUser',
        ),
    ]
