# Generated by Django 6.0.4 on 2026-05-02 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_dbexpense_user_remove_dbexpense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbexpense',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
